services:
  - type: web
    name: almadina-school
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn school_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
